**1. Importei as bibliotecas necessárias**

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle as pkl

**2. Importei os dados**

In [2]:
data = pd.read_csv('breast-cancer-model.csv')
data.head(10)

diagnosis  radius_mean  texture_mean  perimeter_mean  log_smoothness_mean  \
0          1        17.99         10.38          122.80              0.11840   
1          1        20.57         17.77          132.90              0.08474   
2          1        19.69         21.25          130.00              0.10960   
3          1        11.42         20.38           77.58              0.14250   
4          1        20.29         14.34          135.10              0.10030   
5          1        12.45         15.70           82.57              0.12780   
6          1        18.25         19.98          119.60              0.09463   
7          1        13.71         20.83           90.20              0.11890   
8          1        13.00         21.82           87.50              0.12730   
9          1        12.46         24.04           83.97              0.11860   

   log_symmetry_mean  log_concave_points_se  log_radius_worst  \
0             0.2419                0.01587             25.38   
1             0.1812                0.01340             24.99   
2             0.2069                0.02058             23.57   
3             0.2597                0.01867             14.91   
4             0.1809                0.01885             22.54   
5             0.2087                0.01137             15.47   
6             0.1794                0.01039             22.88   
7             0.2196                0.01448             17.06   
8             0.2350                0.01226             15.49   
9             0.2030                0.01432             15.09   

   log_perimeter_worst  log_smoothness_worst  ...  log_concavity_se  \
0               184.60                0.1622  ...          0.052336   
1               158.80                0.1238  ...          0.018429   
2               152.50                0.1444  ...          0.037604   
3                98.87                0.2098  ...          0.055066   
4               152.20                0.1374  ...          0.055321   
5               103.40                0.1791  ...          0.036062   
6               153.20                0.1442  ...          0.022290   
7               110.60                0.1654  ...          0.024576   
8               106.20                0.1703  ...          0.034913   
9                97.65                0.1853  ...          0.074579   

   log_symmetry_se  log_fractal_dimension_se  log_texture_worst  \
0         0.029588                  0.006174           2.908539   
1         0.013794                  0.003526           3.194993   
2         0.022251                  0.004561           3.278276   
3         0.057920                  0.009166           3.314186   
4         0.017408                  0.005102           2.871868   
5         0.021419                  0.005069           3.208825   
6         0.013597                  0.002177           3.355502   
7         0.014751                  0.005397           3.372112   
8         0.021204                  0.003742           3.457263   
9         0.017732                  0.010030           3.730021   

   log_area_worst  log_compactness_worst  log_concavity_worst  \
0        7.610853               0.510185             0.537604   
1        7.579168               0.171092             0.216401   
2        7.444249               0.353821             0.371839   
3        6.343353               0.623958             0.522893   
4        7.362645               0.186480             0.336472   
5        6.610158               0.421929             0.428856   
6        7.382124               0.229205             0.320923   
7        6.800170               0.313496             0.237283   
8        6.607056               0.431847             0.431133   
9        6.568640               0.721735             0.744315   

   log_concave points_worst  log_symmetry_worst  log_fractal_dimension_worst  
0                  0.235388            0.378505                     0.112346  
1           

**3. Separei as variáveis em independênte e dependênte**

In [5]:
y = data['diagnosis']
X = data.drop(['diagnosis'], axis=1)

**4. Dividi os dados em treino e teste**

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

**5. Apliquei o modelo de Regressão Logística**

In [18]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression(max_iter=1000)
logmodel.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

**6. Avaliei o modelo utilizando report e matriz de confusão**

In [19]:
from sklearn.metrics import classification_report, confusion_matrix
predictions = logmodel.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       108
           1       0.97      0.97      0.97        63

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171

[[106   2]
 [  2  61]]


**7. Apliquei o modelo de Árvore de Decisão**

In [10]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

**8. Avaliei o modelo utilizando report e matriz de confusão**

In [11]:
predictions = dtree.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       108
           1       0.89      0.92      0.91        63

    accuracy                           0.93       171
   macro avg       0.92      0.93      0.93       171
weighted avg       0.93      0.93      0.93       171

[[101   7]
 [  5  58]]


**9. Apliquei o modelo de Random Forest**

In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200)

**10. Avaliei o modelo utilizando report e matriz de confusão**

In [13]:
predictions = rfc.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       108
           1       0.98      0.95      0.97        63

    accuracy                           0.98       171
   macro avg       0.98      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171

[[107   1]
 [  3  60]]


**11. Apliquei o modelo de Gradiente Boosting**

In [16]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)

GradientBoostingClassifier()

**12. Avaliei o modelo utilizando report e matriz de confusão**

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
predictions = gbc.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.96      0.97      0.97       108
           1       0.95      0.94      0.94        63

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171

[[105   3]
 [  4  59]]


**13. Exportei o modelo de Logistic Regression em pkl**

In [21]:
pkl.dump(logmodel, open('logmodel.pkl', 'wb'))